[meta]
authors=["bharath-swamy"]
title="Vector search with AI Function EMBED_TEXT"
description="""\
    Learn how to use EMBED_TEXT AI Function in Vector Search and \
    deploy it as a SingleStore CloudFunctions.
    """
icon="browser"
difficulty="beginner"
tags=["notebooks", "python"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="standard"
